/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cenaflix.podcast.view;

/**
 *
 * @author Windows
 */
public class TelaListagem extends javax.swing.JFrame {
private String tipoUsuario;
    /**
     * Creates new form TelaListagem
     */
    // Construtor principal que recebe o tipo do usuário
    public TelaListagem(String tipoUsuario) {
        initComponents();
        this.tipoUsuario = tipoUsuario;
        
        // Verifica quem é para desabilitar botões
        if (tipoUsuario.equalsIgnoreCase("Operador")) {
            btnExcluir.setEnabled(false); // Operador não pode excluir
        } else if (tipoUsuario.equalsIgnoreCase("Usuario")) {
            btnCadastrar.setEnabled(false); // Usuario comum não cadastra
            btnExcluir.setEnabled(false);   // Usuario comum não exclui
        }
    }

    // Construtor vazio (obrigatório para o NetBeans não dar erro visual)
    public TelaListagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPodcasts = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtFiltroProdutor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cenaflix - Listagem de Podcasts");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("CENAFLIX - LISTAGEM");

        tblPodcasts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID.", "Produtor.", "Nome do Episódio.", "Nº do Episódio.", "Duração.", "URL."
            }
        ));
        jScrollPane1.setViewportView(tblPodcasts);

        jLabel2.setText("Pesquisar Produtor:");

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFiltroProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCadastrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFiltroProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnExcluir))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
// Pega a linha selecionada
    int linhaSelecionada = tblPodcasts.getSelectedRow();
    
    if (linhaSelecionada >= 0) {
        // Pega o ID que está na coluna 0 da linha selecionada
        int idPodcast = (int) tblPodcasts.getValueAt(linhaSelecionada, 0);
        
        javax.persistence.EntityManagerFactory emf = javax.persistence.Persistence.createEntityManagerFactory("CenaflixPU");
        javax.persistence.EntityManager em = emf.createEntityManager();
        
        em.getTransaction().begin();
        cenaflix.podcast.model.Podcast p = em.find(cenaflix.podcast.model.Podcast.class, idPodcast);
        em.remove(p);
        em.getTransaction().commit();
        
        em.close();
        emf.close();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
        // Clique no botão pesquisar via código para atualizar a tabela
        // Você pode copiar o código do pesquisar aqui ou simplesmente pedir para o usuário pesquisar de novo.
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma linha para excluir.");
    }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try {
        // 1. Conectar ao banco
        javax.persistence.EntityManagerFactory emf = javax.persistence.Persistence.createEntityManagerFactory("CenaflixPU");
        javax.persistence.EntityManager em = emf.createEntityManager();
        
        // 2. Criar a consulta (Buscar podcast onde produtor pareça com o que foi digitado)
        // ATENÇÃO: Se ficar vermelho no "Podcast", clique na lampadinha e escolha "Import cenaflix.podcast.model.Podcast"
        String filtro = txtFiltroProdutor.getText();
        java.util.List<cenaflix.podcast.model.Podcast> lista = em.createQuery(
            "SELECT p FROM Podcast p WHERE p.produtor LIKE :produtor", cenaflix.podcast.model.Podcast.class)
            .setParameter("produtor", "%" + filtro + "%")
            .getResultList();
        
        // 3. Jogar os dados na Tabela
        javax.swing.table.DefaultTableModel tabela = (javax.swing.table.DefaultTableModel) tblPodcasts.getModel();
        tabela.setRowCount(0); // Limpa a tabela antes de encher
        
        for (cenaflix.podcast.model.Podcast p : lista) {
            tabela.addRow(new Object[]{ 
                p.getId(), 
                p.getProdutor(), 
                p.getNomeEpisodio(), 
                p.getNumeroEpisodio(), 
                p.getDuracao(), 
                p.getUrlRepo() 
            });
        }
        
        // 4. Fechar conexão
        em.close();
        emf.close();
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao pesquisar: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
TelaCadastro tela = new TelaCadastro();
    tela.setVisible(true);
    // Não fechamos a listagem, deixamos ela aberta atrás
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPodcasts;
    private javax.swing.JTextField txtFiltroProdutor;
    // End of variables declaration//GEN-END:variables
}
